### ISSUE TITLE
getting error when building ni package

### ISSUE THREAD

**Issue by brandonzx3** [jsimpso81/PhotonVisionLabVIEW#1]
after making changes to my copy, I am able to build the project files but the ni packages failed to build with this error.

`Error 42 occurred at PKG.lvlib:Build Source.lvclass:Check for Missing Files.vi -> PKG.lvlib:Package.lvclass:Check for Missing Files.vi`

**Comment by jsimpso81** [comment]
Does the rest of the message indicate which file is missing?

Try the following:
- Right click on the project and select "mass compile" or maybe just "compile".   This will locate external library items that may have changed location.
- Ensure that the source build definition is built first.  After that then build the 2 package build definitions.
- Suggest "cleaning" all three build definitions before building any, especially if this is the first time.  (Right click on build definition and select CLEAN.)
- Windows has an interesting issue (limitation) with maximum file length.  This can cause the build process to fail with interesting errors.  Suggest putting the root of the github repository in a directory with a short path length.  I have used C:\shares\github\PVL\  with success.

Let me know if this fixes your issue.

**Comment by brandonzx3** [comment]
Hi. Thank you for letting me know about the mass compile feature in labview. After running that It solved the issue.

**Comment by jsimpso81** [comment]
Closed.
